base_url = "https://www.cs.cornell.edu/courses/cs6120/2025sp"
compile_sass = true
build_search_index = false

generate_feeds = true

title = "CS 6120"

[markdown]
smart_punctuation = true
highlight_code = true
highlight_theme = "subway-madrid"

[extra]
favicon = "/img/favicon.ico"
bigicon = "/img/favicon152.png"

[[extra.links]]
name = "Zulip"
url = "https://cs6120.zulipchat.com"

[[extra.links]]
name = "Discussions"
url = "https://github.com/sampsyo/cs6120/discussions"
