on:
  push:
    branches:
      - 2025sp
  pull_request:
    branches:
      - 2025sp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Zola'
        run: sudo snap install --edge zola
      - name: 'Build Zola site'
        run: zola build --drafts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{github.event_name=='push' && github.ref=='refs/heads/2025sp'}}
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: public
      - run: ls -R
      - name: rsync
        env:
          DEPLOY_HOST: cslinux.cs.cornell.edu
          DEPLOY_USER: als485
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          DEPLOY_SRC: ./public/
          DEPLOY_DEST: /courses/cs6120/2025sp/site
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          rsync --compress --recursive --checksum --itemize-changes --delete \
            --perms --chmod=Du=rwx,Dgo=rx,Fu=rw,Fog=r \
            -e "ssh -i pk -o 'UserKnownHostsFile kh'" \
            $DEPLOY_SRC $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DEST
